server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 10
  server:
    wait-time-in-ms-when-sync-empty: 10000
    renewal-percent-threshold: 0.65

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF