server:
  port: ${RESOLVER_SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: resolver-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DATABASE}

    redis:
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      client-type: lettuce
      cluster:
        nodes:
          - ${REDIS_NODE_1}
          - ${REDIS_NODE_2}
          - ${REDIS_NODE_3}
          - ${REDIS_NODE_4}
          - ${REDIS_NODE_5}
          - ${REDIS_NODE_6}
      timeout: ${REDIS_TIMEOUT}
  cache:
    type: ${SPRING_CACHE_TYPE}

springdoc:
  swagger-ui:
    path: /swagger-ui.html