version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/shortener-service"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
  - package-ecosystem: "maven"
    directory: "/keygen-service"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
  - package-ecosystem: "maven"
    directory: "/resolver-service"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"