name: Java CI on main branch

on:
  push:
    branches: [ main ]

jobs:
  build-and-analyze:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Start Keygen container
        run: |
          docker pull isaacandra/keygen:latest
          docker run -d -p 8085:8085 --name keygen \
            -e KEYGEN_SERVER_PORT=8085 \
            isaacandra/keygen:latest \
            sleep 20

      - name: Build and analyze
        run: mvn -B verify
