name: Java CI for Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  keygen:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and run Keygen container
        run: |
          docker pull isaacandra/keygen:latest
          docker run -d -p 8080:8080 --name keygen \
            -e KEYGEN_SERVER_PORT=8080 \
            isaacandra/keygen:latest

      - name: Wait for Keygen to be ready
        run: |
          for i in {1..20}; do
            if curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
              echo "Keygen is up"
              break
            fi
            echo "Waiting for Keygen..."
            sleep 3
          done

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build all modules
        run: mvn clean install -DskipTests

      - name: Run all tests
        run: mvn test