name: Java CI for Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup-keygen-service:
    name: Setup Keygen Service
    runs-on: ubuntu-latest
    steps:
      - name: Start Keygen container
        run: |
          docker pull isaacandra/keygen:latest
          docker run -d -p 8085:8085 --name keygen-service \
            -e KEYGEN_SERVER_PORT=8085 \
            isaacandra/keygen:latest \
          sleep 20

  test:
    runs-on: ubuntu-latest
    name: Execute Tests
    needs: setup-keygen-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build all modules
        run: mvn clean install -DskipTests

      - name: Run all tests
        run: mvn test