name: Java CI on main branch

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      keygen:
        image: isaacandra/keygen:latest
        ports:
          - 8085:8085
        env:
          KEYGEN_SERVER_PORT: 8085
        options: >-
          --health-cmd="curl --fail http://localhost:8080/actuator/health || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and analyze
        run: mvn -B verify